@extends('layouts.guru-workspace')

@section('title', 'Data Rapor')

@section('content')
<section class="mx-auto max-w-7xl">
    <div><p class="rk-eyebrow">Penyusunan Rapor</p><h1 class="mt-2 text-3xl font-extrabold text-[#102d4b]">Data Rapor</h1><p class="mt-2 text-sm text-slate-500">Periksa status nilai dan deskripsi sebelum membuka preview atau mencetak rapor.</p></div>
    <div class="mt-7">@include('guru.wali.partials.filters', ['filterAction' => route('guru.wali.rapor.index')])</div>
    <div class="mt-6 grid gap-4 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Belum Lengkap</p><strong class="mt-2 block text-3xl text-slate-700">{{ $studentRows->where('reportStatus', 'Belum Lengkap')->count() }}</strong></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Perlu Ditinjau</p><strong class="mt-2 block text-3xl text-amber-700">{{ $studentRows->where('reportStatus', 'Perlu Ditinjau')->count() }}</strong></div><div id="siap-cetak" class="scroll-mt-28 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p class="text-sm text-emerald-700">Siap Dicetak</p><strong class="mt-2 block text-3xl text-emerald-800">{{ $studentRows->where('reportStatus', 'Siap Dicetak')->count() }}</strong></div></div>
    <div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-4">Siswa</th><th class="px-5 py-4">Status Nilai</th><th class="px-5 py-4">Status Deskripsi</th><th class="px-5 py-4">Status Rapor</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse ($studentRows as $row)<tr><td class="px-5 py-4"><strong class="text-[#102d4b]">{{ $row['student']->nama }}</strong><small class="block text-slate-500">NIS {{ $row['student']->nis }}</small></td><td class="px-5 py-4">{{ $row['allScoresComplete'] ? 'Lengkap' : $row['missingScoreCount'].' nilai belum lengkap' }}</td><td class="px-5 py-4">{{ $row['allDescriptionsValidated'] ? 'Tervalidasi' : 'Perlu ditinjau' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $row['readyToPrint'] ? 'bg-emerald-50 text-emerald-700' : ($row['allScoresComplete'] ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600') }}">{{ $row['reportStatus'] }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('guru.wali.rapor.show', ['siswa' => $row['student'], 'tahun_ajaran_id' => $selectedSchoolYear?->id]) }}" class="font-bold text-emerald-700">Buka Rapor</a></td></tr>@empty<tr><td colspan="5" class="px-6 py-14 text-center text-slate-500">Belum ada siswa atau data rapor pada periode ini.</td></tr>@endforelse</tbody></table></div></div>
</section>
@endsection
