@extends('layouts.guru-workspace')

@section('title', 'Preview Rapor '.$studentRow['student']->nama)

@section('content')
<section class="mx-auto max-w-6xl">
    <div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('guru.wali.rapor.index', ['kelas_id' => $selectedClass?->id, 'tahun_ajaran_id' => $selectedSchoolYear?->id]) }}" class="text-sm font-bold text-emerald-700">← Data Rapor</a><p class="rk-eyebrow mt-5">Preview Rapor</p><h1 class="mt-2 text-3xl font-extrabold text-[#102d4b]">{{ $studentRow['student']->nama }}</h1></div><div class="flex flex-wrap gap-3">@if ($studentRow['readyToPrint'])<a href="{{ route('guru.wali.rapor.print', ['siswa' => $studentRow['student'], 'tahun_ajaran_id' => $selectedSchoolYear?->id]) }}" class="rk-button rk-button-primary"><x-nav-icon name="printer" /> Cetak / Simpan PDF</a>@else<span class="rk-button cursor-not-allowed bg-slate-200 text-slate-500" aria-disabled="true" title="Lengkapi nilai dan deskripsi terlebih dahulu.">Cetak Belum Tersedia</span>@endif</div></div>
    @unless ($studentRow['readyToPrint'])<div class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800"><strong class="block">Rapor belum siap dicetak.</strong><span class="mt-1 block">{{ $studentRow['missingScoreCount'] }} nilai belum lengkap. Pastikan seluruh deskripsi juga sudah divalidasi.</span></div>@endunless
    <article class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><header class="border-b-2 border-[#102d4b] pb-6 text-center"><p class="text-xs font-extrabold uppercase tracking-[0.2em] text-emerald-700">RaporKu</p><h2 class="mt-2 text-2xl font-extrabold text-[#102d4b]">Laporan Hasil Belajar</h2><p class="mt-1 text-sm text-slate-500">{{ $selectedSchoolYear?->tahun }} · Semester {{ $selectedSchoolYear?->semester }}</p></header><dl class="mt-6 grid gap-x-8 gap-y-3 text-sm sm:grid-cols-2"><div class="flex justify-between border-b border-slate-100 py-2"><dt class="text-slate-500">Nama</dt><dd class="font-bold">{{ $studentRow['student']->nama }}</dd></div><div class="flex justify-between border-b border-slate-100 py-2"><dt class="text-slate-500">NIS / NISN</dt><dd class="font-bold">{{ $studentRow['student']->nis }} / {{ $studentRow['student']->nisn ?: '—' }}</dd></div><div class="flex justify-between border-b border-slate-100 py-2"><dt class="text-slate-500">Kelas</dt><dd class="font-bold">{{ $selectedClass?->tingkat }} {{ $selectedClass?->nama }}</dd></div><div class="flex justify-between border-b border-slate-100 py-2"><dt class="text-slate-500">Wali Kelas</dt><dd class="font-bold">{{ $guru->nama }}</dd></div></dl>
        <div class="mt-8 overflow-x-auto"><table class="min-w-full border-collapse text-left text-sm"><thead><tr class="bg-slate-100"><th class="border border-slate-300 px-4 py-3">Mata Pelajaran</th><th class="border border-slate-300 px-4 py-3 text-center">Nilai</th><th class="border border-slate-300 px-4 py-3 text-center">KKM</th><th class="border border-slate-300 px-4 py-3">Deskripsi</th></tr></thead><tbody>@foreach ($studentRow['subjects'] as $subject)<tr><td class="border border-slate-300 px-4 py-3 font-bold">{{ $subject['assignment']->mataPelajaran->nama }}</td><td class="border border-slate-300 px-4 py-3 text-center">{{ $subject['average'] === null ? '—' : number_format($subject['average'], 2, ',', '.') }}</td><td class="border border-slate-300 px-4 py-3 text-center">{{ number_format((float) $subject['assignment']->mataPelajaran->kkm, 0, ',', '.') }}</td><td class="border border-slate-300 px-4 py-3 leading-6">{{ $subject['description']?->deskripsi_akhir ?: 'Deskripsi belum ditinjau.' }}</td></tr>@endforeach</tbody></table></div>
    </article>
</section>
@endsection
