@extends('layouts.guru-workspace')

@section('title', 'Deskripsi Rapor')

@section('content')
<section class="mx-auto max-w-7xl">
    <div><p class="rk-eyebrow">Penyusunan Rapor</p><h1 class="mt-2 text-3xl font-extrabold text-[#102d4b]">Deskripsi Rapor</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Saran sistem dibuat dari nilai dan tren nyata. Wali kelas tetap wajib meninjau, mengedit, dan memvalidasinya.</p></div>
    <div class="mt-7">@include('guru.wali.partials.filters', ['filterAction' => route('guru.wali.deskripsi.index')])</div>

    <form method="GET" action="{{ route('guru.wali.deskripsi.index') }}" class="mt-5 grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><input type="hidden" name="kelas_id" value="{{ $selectedClass?->id }}"><input type="hidden" name="tahun_ajaran_id" value="{{ $selectedSchoolYear?->id }}"><div><label for="siswa_id" class="text-xs font-bold text-slate-600">Siswa</label><select id="siswa_id" name="siswa_id" class="rk-field mt-2">@foreach ($studentRows as $row)<option value="{{ $row['student']->id }}" @selected($studentRow && $studentRow['student']->id === $row['student']->id)>{{ $row['student']->nama }}</option>@endforeach</select></div><div><label for="pengampu_id" class="text-xs font-bold text-slate-600">Mata pelajaran</label><select id="pengampu_id" name="pengampu_id" class="rk-field mt-2">@foreach ($assignments as $assignment)<option value="{{ $assignment->id }}" @selected($subject && $subject['assignment']->id === $assignment->id)>{{ $assignment->mataPelajaran->nama }}</option>@endforeach</select></div><button class="rk-button rk-button-primary">Tampilkan</button></form>

    @if ($studentRow && $subject)
        <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
            <aside class="grid content-start gap-4"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs font-bold uppercase text-slate-400">Ringkasan Data</p><h2 class="mt-2 text-xl font-extrabold text-[#102d4b]">{{ $studentRow['student']->nama }}</h2><p class="mt-1 text-sm text-slate-500">{{ $subject['assignment']->mataPelajaran->nama }}</p><dl class="mt-5 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Rata-rata</dt><dd class="mt-1 font-extrabold">{{ $subject['average'] === null ? '—' : number_format($subject['average'], 2, ',', '.') }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Tren</dt><dd class="mt-1 font-extrabold">{{ $subject['trend']['label'] }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">KKM</dt><dd class="mt-1 font-extrabold">{{ number_format((float) $subject['assignment']->mataPelajaran->kkm, 0, ',', '.') }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Belum lengkap</dt><dd class="mt-1 font-extrabold">{{ $subject['missingCount'] }}</dd></div></dl></div><div class="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-sm leading-6 text-blue-900"><strong class="block">Saran sistem — silakan tinjau sebelum disimpan.</strong><p class="mt-2">{{ $subject['suggestion'] }}</p></div></aside>
            <article class="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 class="text-lg font-bold text-[#102d4b]">Tinjau Deskripsi</h2><p class="mt-1 text-sm text-slate-500">Sesuaikan bahasa dengan pengamatan wali kelas. Saran tidak otomatis dianggap final.</p>
                @if ($subject['referenceScore'])
                    <form method="POST" action="{{ route('guru.wali.deskripsi.update', ['pengampu' => $subject['assignment'], 'siswa' => $studentRow['student']]) }}" class="mt-5 grid gap-5" data-loading-form>@csrf @method('PUT')<div><label for="deskripsi_akhir" class="text-sm font-bold text-slate-700">Deskripsi akhir</label><textarea id="deskripsi_akhir" name="deskripsi_akhir" rows="9" class="rk-field mt-2 min-h-52" @if ($errors->has('deskripsi_akhir')) aria-invalid="true" aria-describedby="deskripsi-error" @endif>{{ old('deskripsi_akhir', $subject['description']?->deskripsi_akhir ?? $subject['suggestion']) }}</textarea>@error('deskripsi_akhir')<p id="deskripsi-error" class="mt-2 text-sm font-semibold text-red-600" role="alert">{{ $message }}</p>@enderror</div><div><label for="status" class="text-sm font-bold text-slate-700">Status</label><select id="status" name="status" class="rk-field mt-2" @if ($errors->has('status')) aria-invalid="true" aria-describedby="status-error" @endif><option value="draft" @selected(old('status', $subject['description']?->status ?? 'draft') === 'draft')>Simpan sebagai draf</option><option value="tervalidasi" @selected(old('status', $subject['description']?->status) === 'tervalidasi') @disabled(! $subject['isComplete'])>Validasi sebagai deskripsi final</option></select>@error('status')<p id="status-error" class="mt-2 text-sm font-semibold text-red-600" role="alert">{{ $message }}</p>@enderror @unless ($subject['isComplete'])<p class="mt-2 text-xs text-amber-700">Lengkapi seluruh nilai mata pelajaran ini sebelum validasi final.</p>@endunless</div><div class="flex flex-wrap gap-3"><button type="submit" class="rk-button rk-button-primary"><span data-submit-label>Simpan Deskripsi</span></button><a href="{{ route('guru.wali.rapor.show', ['siswa' => $studentRow['student'], 'tahun_ajaran_id' => $selectedSchoolYear?->id]) }}" class="rk-button rk-button-secondary">Preview Rapor</a></div></form>
                @else
                    <div class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Deskripsi belum dapat disimpan karena belum ada nilai referensi pada mata pelajaran ini.</div>
                @endif
            </article>
        </div>
    @else
        <div class="mt-6 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center text-sm text-slate-500">Pilih kelas dengan siswa dan mata pelajaran untuk mulai menyusun deskripsi.</div>
    @endif
</section>
@endsection
